const ENV = process.env;

module.exports = {
  NOTION_TOKEN: ENV.NOTION_TOKEN,
  NOTION_DATABASE_ID: ENV.NOTION_DATABASE_ID,
  GOOGLE_SERVICE_ACCOUNT_KEY: ENV.GOOGLE_SERVICE_ACCOUNT_KEY,
  MANAGEMENT_SPREADSHEET_ID: ENV.MANAGEMENT_SPREADSHEET_ID,
  ACADEMIC_SPREADSHEET_ID: ENV.ACADEMIC_SPREADSHEET_ID,
  PLAN_MIN_LENGTH: 150,
  WEEK_REGEX: /po\d{2}-(\d{2})/i,
  JAPANESE_WEEKDAYS: ['日', '月', '火', '水', '木', '金', '土'],
  IS_CI: ENV.GITHUB_ACTIONS === 'true',
};
